### ISSUE TITLE
[DOC]: All the flutter_sound documentation links in the readme are broken

### ISSUE THREAD

**Issue by lorg** [Canardoux/tau#640]
Looking at the readme, it says "flutter_sound user, your documentation is here: https://tau.canardoux.xyz/readme.html ", but that link (which appears in other places as well) is broken.

**Comment by davidAg9** [comment]
same here 
.....I am reading the documentation to implement my flutter project  to meet a deadline...please bring it up fast.....

**Comment by Larpoux** [comment]
I am really sorry. The server had a crash and I had to reinstall everything.

Probably everything will be stable in one hour or two.

**Comment by davidAg9** [comment]
the server is back up 
thank you

**Comment by davidAg9** [comment]
website sorry, and final request is support for flutter 2 (null-safety)....thank you again 👍🏽 cheers

**Comment by Larpoux** [comment]
OK.
The server is back :-)

Just a last problem with the "Live Demo on Web".

Sorry for this bad day ...

**Comment by davidAg9** [comment]
at least it was resolve within the day....although I have lost some hours ....it better than it not resolve at all
Flutter sound is a great package ,and have just displayed fast response and reliability ......cheers ...its safe to close this issue after an hour

**Comment by bafplus** [comment]
Dont know if related but some links to git are not working.
For example: https://tau.canardoux.xyz/tau_api_player_startPlayer.html has a link to "startplayer()" but that page gives 404.
There are a lot of such referances/links that give a 404.

**Comment by Larpoux** [comment]
Hi everybody.
I just released a new Flutter Sound 8.2.0.  I hope that everything OK.

The problem with the API documentation is that "dartdoc" crashes on my machine.
I am not able to generate the dart API.
I think that my problem is because I use a Macintosh with an Apple Silicon M1 chip.
The M1 is globally good for developments. But a few tools does not work correctely.

**Comment by bafplus** [comment]
I also noticed that the demo doesnt work anymore. Northing happends in the players, i guess thats related since they worked yesterday?

**Comment by Larpoux** [comment]
No, this is not OK. The demo should work.
The canardoux server was not able to serve the example because of a Cors security issue. But I fixed that a few days ago.

Edited : you are right. The demo does not work .
😢 
I am going to fix that. Thank you for your remark.

**Comment by Larpoux** [comment]
OK. I think that the problem with the live demo is fixed.
I am going now to see if I really cannot generate this f***g doc of the API

**Comment by bafplus** [comment]
Players work in the demo on my end, but recorders still don't. So halfway there ;-)

**Comment by Larpoux** [comment]
Try the Simple Recorder demo. It is OK on chrome on my machine.
Wich brpwser do you use ?

**Comment by Larpoux** [comment]
OPUS/WEBM is OK on chrome.
The browsers have very few codecs working for recording.
In fact just one !  But it is not the same on Webkit (safari and all the browsers on iOS) and on Chrome/Firefox

**Comment by bafplus** [comment]
I use chrome, i get this error when hitting a record button: Uncaught (in promise) DOMException: Requested device not found

**Comment by Larpoux** [comment]
I think that it is a problem with your browser sandbox. But not sure. I do not master very well the authorizations needed to record.

**Comment by bafplus** [comment]
Doesent work on my laptop (it did yesterday), does work when on mobile (chrome). So indeed seems a local problem...

**Comment by Larpoux** [comment]
Yes. Correct. Probably a local problem on your browser.

BTW : next week I will begin to port the Dart code to javascript/typescript. I will have some Fun 🙄

**Comment by Larpoux** [comment]
> The problem with the API documentation is that "dartdoc" crashes on my machine.
> I am not able to generate the dart API.
> I think that my problem is because I use a Macintosh with an Apple Silicon M1 chip.
> The M1 is globally good for developments. But a few tools do not work correctly.

This is fixed : now I build the Flutter API documentation on Canardoux which is a x86 Linux Server.

If you get some 404 (there are plenty of them!) please reopen this issue and specify the faulting page.
